### ISSUE TITLE
Can't install on ubuntu. Ruby can't find gem 'wpk'

### ISSUE THREAD

**Issue by kactetus** [ablebeam/apify-kit#1]
Tnx for app interested by your app, but have error. When I enter in console $ bundle install have this error

http://i.imgbox.com/Fw0gv7xZ.png
root@kali:~/work/apify-kit# bundle install
Don't run Bundler as root. Bundler can ask for sudo if it is needed, and
installing your bundle as root will break this application for all non-root
users on this machine.
Fetching gem metadata from https://rubygems.org/.........
Fetching version metadata from https://rubygems.org/...
Fetching dependency metadata from https://rubygems.org/..
Could not find gem 'wpk (>= 0) ruby' in source at ../wpk.
Source does not contain any versions of 'wpk (>= 0) ruby'

Ruby can't find 'wpk' gem. How do I fix it? Tnanks in advance.

And have error in clone repo. To install app need clone buy this 
$ git clone https://github.com/ablebeam/apify-kit

**Comment by ablebeam** [comment]
Hello!
Thanks for your attantion!
As you can see, I've stopped maintaining this app about a year ago. I've also changed github username during this time - thats why git clone from docs doesn't work

WPK gem was an attempt to refactor and improve current code but it was not finished and has never been released. Looks like it was accidentally added to master branch. So you can simply remove it from Gemfile and everything should work

But documentation is still poor. If you are really intersted in this app I can try to make better docs and and some deployment guide or Ansible playbook

Also you can first check Apify::Core gem located at /core of this app - this is a main "parsing" logic.

**Comment by kactetus** [comment]
Tnx for reply. I can't make it work properly. I start Redis and thne Foreman.  And when i go to http://localhost:5000/users/sign_in
We're sorry, but something went wrong.
If you are the application owner check the logs for more information.

and in production.log
I, [2016-05-18T01:19:36.912445 #13062]  INFO -- : Started GET "/users/sign_in" for 127.0.0.1 at 2016-05-18 01:19:36 +0300
I, [2016-05-18T01:19:36.913336 #13062]  INFO -- : Processing by Devise::SessionsController#new as HTML
I, [2016-05-18T01:19:36.914320 #13062]  INFO -- : Completed 500 Internal Server Error in 1ms
F, [2016-05-18T01:19:36.932465 #13062] FATAL -- : 
ActiveRecord::StatementInvalid (Could not find table 'users'):
  activerecord (4.1.8) lib/active_record/connection_adapters/sqlite3_adapter.rb:515:in `table_structure'
  activerecord (4.1.8) lib/active_record/connection_adapters/sqlite3_adapter.rb:390:in `columns'

but i can't connect to db.
